/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipenampilgambar;

import java.awt.CardLayout;

/**
 *
 * @author User
 */
public class AplikasiPenampilGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPenampilGambarButton
     */
    public AplikasiPenampilGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPanel = new javax.swing.JPanel();
        Gbr1BTN = new javax.swing.JButton();
        Gbr2BTN = new javax.swing.JButton();
        Gbr3BTN = new javax.swing.JButton();
        ExitBTN = new javax.swing.JButton();
        ImagePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Gbr1BTN.setText("Gambar 1");
        Gbr1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gbr1BTNActionPerformed(evt);
            }
        });
        ButtonPanel.add(Gbr1BTN);

        Gbr2BTN.setText("Gambar 2");
        Gbr2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gbr2BTNActionPerformed(evt);
            }
        });
        ButtonPanel.add(Gbr2BTN);

        Gbr3BTN.setText("Gambar 3");
        Gbr3BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gbr3BTNActionPerformed(evt);
            }
        });
        ButtonPanel.add(Gbr3BTN);

        ExitBTN.setText("EXIT");
        ExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTNActionPerformed(evt);
            }
        });
        ButtonPanel.add(ExitBTN);

        getContentPane().add(ButtonPanel, java.awt.BorderLayout.PAGE_START);

        ImagePanel.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenampilgambar/gambar 1.jpeg"))); // NOI18N
        ImagePanel.add(jLabel1, "1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenampilgambar/gambar 2.jpeg"))); // NOI18N
        ImagePanel.add(jLabel2, "2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenampilgambar/gambar 3.jpeg"))); // NOI18N
        ImagePanel.add(jLabel3, "3");

        getContentPane().add(ImagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Gbr1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gbr1BTNActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) (ImagePanel.getLayout());
        c1.show(ImagePanel, "1");
    }//GEN-LAST:event_Gbr1BTNActionPerformed

    private void Gbr2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gbr2BTNActionPerformed
        // TODO add your handling code here:
         CardLayout c1 = (CardLayout) (ImagePanel.getLayout());
        c1.show(ImagePanel, "2");
    }//GEN-LAST:event_Gbr2BTNActionPerformed

    private void Gbr3BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gbr3BTNActionPerformed
        // TODO add your handling code here:
         CardLayout c1 = (CardLayout) (ImagePanel.getLayout());
        c1.show(ImagePanel, "3");
    }//GEN-LAST:event_Gbr3BTNActionPerformed

    private void ExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenampilGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JButton ExitBTN;
    private javax.swing.JButton Gbr1BTN;
    private javax.swing.JButton Gbr2BTN;
    private javax.swing.JButton Gbr3BTN;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
